Исправление задание 1 и 2
LordOfTheHouse/TestJunit pull request #2
Opened 2022-07-07 07:50 UTC by LordOfTheHouse

2022-07-09 19:20 UTC, XLelarX requested changes

2022-07-09 19:20 UTC, XLelarX commented on src/main/java/com/example/Reptiloyd.java
>      private int NumberOfHumans;
Название поля с маленькой буквы

2022-07-09 19:20 UTC, XLelarX commented on src/main/java/com/example/stream/StreamWork.java
> +						.flatMap(x -> List.of(x.getKey(), x.getValue()).stream()).toList();
Что за toList? Используй collect
Отступ перед flatMap поехал
Вместо List.of и перевода его в стрим надо просто сделать Stream.of

2022-07-09 19:20 UTC, XLelarX commented on src/main/java/com/example/lambda/LambdaWork.java
> +	final static int digit = 20;
константа класса

2022-07-09 19:20 UTC, XLelarX commented on src/main/java/com/example/lambda/LambdaWork.java
> +				return digit +  d;
Пробелы поехали. Юзай идеевское форматирование

2022-07-09 19:20 UTC, XLelarX commented on src/main/java/com/example/lambda/OneArgumentFunctionalInterface.java
> +package  com.example.lambda;
пробел. В остальных ФИ тоже

2022-07-09 19:20 UTC, XLelarX commented on src/main/java/com/example/stream/StreamWork.java
> +				.collect(Collectors.toMap(key -> key, key -> key.length()));
Функции типа key -> key надо заменять на Function.identity()
А вторую можно заменить на String::length

2022-07-09 19:20 UTC, XLelarX commented on src/main/java/com/example/stream/StreamWork.java
> +		mp.entrySet().forEach(System.out::println);
Для простого вывода коллекции не обязательно писать цикл, оно норм выведется через sout.
Можешь не править, это на будущее)

2022-07-09 19:20 UTC, XLelarX commented on src/main/java/com/example/lambda/LambdaWork.java
> +	public static int getTen(OneArgumentFunctionalInterface one) {
Название getTen не отражает суть метода. По сути ()-> 10 - getTen, а не этот метод. Тоже на будущее

2022-07-11 15:35 UTC, XLelarX requested changes

2022-07-11 15:35 UTC, XLelarX commented on src/test/java/com/example/LambdaWorkTest.java
> +package com.example;
Не в том пакете

2022-07-11 15:35 UTC, XLelarX commented on src/test/java/com/example/StreamWorkTest.java
> +package com.example;
Не в том пакете

2022-07-11 15:35 UTC, XLelarX commented on src/main/java/com/example/lambda/LambdaWork.java
> +  public static int FunctionOneArgument(TwoArgumentFunctionalInterface two) {
Метод с маленькой буквы должен быть

2022-07-11 15:35 UTC, XLelarX commented on src/main/java/com/example/stream/StreamWork.java
> +    double averageLi = li
переменная не нужна, можно просто сделать return. Ниже аналогично

2022-07-11 15:35 UTC, XLelarX commented on src/main/java/com/example/stream/StreamWork.java
> +    HashMap<String, String> map
Тут надо юзать Map, а не HashMap. Ниже аналогично

2022-07-11 15:35 UTC, XLelarX commented on src/test/java/com/example/stream/StreamWorkTest.java
> +    HashMap<String, String> map = new HashMap<>();
Мапа тут и ниже - дубликаты

2022-07-11 15:35 UTC, XLelarX commented on src/test/java/com/example/stream/StreamWorkTest.java
> +    assertEquals(null, StreamWork.getMap(set).get("we"));
StreamWork.getMap(set) в переменную

2022-07-11 15:35 UTC, XLelarX commented on src/test/java/com/example/stream/StreamWorkTest.java
> +    assertTrue(StreamWork.getKeyDoubleEqualValue(map).contains("5 == five"));
StreamWork.getKeyDoubleEqualValue(map) в переменную

2022-07-11 15:35 UTC, XLelarX commented on src/test/java/com/example/stream/StreamWorkTest.java
> +    assertTrue(StreamWork.getListKeyAndValue(map).contains("one"));
StreamWork.getListKeyAndValue(map) в переменную

2022-07-11 15:59 UTC, LordOfTheHouse commented on src/test/java/com/example/LambdaWorkTest.java
> +package com.example;
+

2022-07-11 15:59 UTC, LordOfTheHouse commented on src/test/java/com/example/StreamWorkTest.java
> +package com.example;
+

2022-07-11 15:59 UTC, LordOfTheHouse commented on src/main/java/com/example/lambda/LambdaWork.java
> +  public static int FunctionOneArgument(TwoArgumentFunctionalInterface two) {
+

2022-07-11 16:00 UTC, LordOfTheHouse commented on src/test/java/com/example/stream/StreamWorkTest.java
> +    assertTrue(StreamWork.getKeyDoubleEqualValue(map).contains("5 == five"));
+

2022-07-11 16:00 UTC, LordOfTheHouse commented on src/test/java/com/example/stream/StreamWorkTest.java
> +    assertEquals(null, StreamWork.getMap(set).get("we"));
+

2022-07-11 16:00 UTC, LordOfTheHouse commented on src/test/java/com/example/stream/StreamWorkTest.java
> +    HashMap<String, String> map = new HashMap<>();
+

2022-07-11 16:00 UTC, LordOfTheHouse commented on src/main/java/com/example/stream/StreamWork.java
> +    HashMap<String, String> map
+

2022-07-11 16:00 UTC, LordOfTheHouse commented on src/main/java/com/example/stream/StreamWork.java
> +    double averageLi = li
+

2022-07-11 16:25 UTC, XLelarX approved these changes

2022-07-11 16:25 UTC, merged