Test unit
LordOfTheHouse/TestJunit pull request #3
Opened 2022-07-11 18:00 UTC by LordOfTheHouse

2022-07-11 21:03 UTC, XLelarX requested changes

2022-07-11 21:03 UTC, XLelarX commented on src/test/java/com/example/reflection/RoomTest.java
> +        privateField.set(room, 3);
set -> setInt

2022-07-11 21:03 UTC, XLelarX commented on src/test/java/com/example/reflection/RoomTest.java
> +        int size = (int) privateField.get(room);
get -> getInt

2022-07-12 03:39 UTC, LordOfTheHouse commented on src/test/java/com/example/reflection/RoomTest.java
> +        privateField.set(room, 3);
Поправил

2022-07-12 03:39 UTC, LordOfTheHouse commented on src/test/java/com/example/reflection/RoomTest.java
> +        int size = (int) privateField.get(room);
Поправил

2022-07-12 06:03 UTC, XLelarX approved these changes

2022-07-12 06:03 UTC, merged