Thread
LordOfTheHouse/TestJunit pull request #4
Opened 2022-07-12 18:57 UTC by LordOfTheHouse

2022-07-12 20:56 UTC, XLelarX requested changes

2022-07-12 20:56 UTC, XLelarX commented on src/test/java/com/example/thread/ThreadProgrammTest.java
> +        Object lock = new Object();
Тест для 5 таски написан неверно

2022-07-12 20:56 UTC, XLelarX commented on src/test/java/com/example/thread/ThreadProgrammTest.java
> +    public void interrupting() {
вот это подойдет под 6 задачку, а 3 задачку можно сделать через простое создание потока-демона

2022-07-13 07:39 UTC, LordOfTheHouse commented on src/test/java/com/example/thread/ThreadProgrammTest.java
> +        Object lock = new Object();
исправлено

2022-07-13 07:39 UTC, LordOfTheHouse commented on src/test/java/com/example/thread/ThreadProgrammTest.java
> +    public void interrupting() {
исправлено

2022-07-13 11:21 UTC, XLelarX approved these changes

2022-07-13 11:22 UTC, merged